export const LOAD_DAILY_PICTURES_SUCCESS = 'LOAD_DAILY_PICTURES_SUCCESS';
export const LOAD_DAILY_PICTURE_SUCCESS = 'LOAD_DAILY_PICTURE_SUCCESS';
export const UPLOAD_DAILY_PICTURE_SUCCESS = 'UPLOAD_DAILY_PICTURE_SUCCESS';
export const LOADING_DAILY_PICTURE = 'LOADING_DAILY_PICTURE';
