export const LOAD_DAILY_PICTURES_SUCCESS = 'LOAD_DAILY_PICTURES_SUCCESS';
export const UPLOAD_DAILY_PICTURE_SUCCESS = 'UPLOAD_DAILY_PICTURE_SUCCESS';
export const UPLOADING_PICTURE = 'UPLOADING_PICTURE';
